### ISSUE TITLE
Add support for PUT when uploading charts

### ISSUE THREAD

**Issue by ssoerensen** [kubernetes-helm/chartmuseum#111] opened 2018-04-25 07:45 UTC
I think it would be a great idea to add support for using HTTP PUT when uploading charts

**Comment by jdolitsky** [comment] 2018-04-25 07:46
@ssoerensen can you explain further? Do you intend to overwrite an existing chart? This is what the `--allow-overwrite` option was intended for, and you can reuse the POST /api/charts endpoint

**Comment by ssoerensen** [comment] 2018-04-25 07:57
Basically i would like to use the https://github.com/kiwigrid/helm-maven-plugin. As of now it uses PUT. I know that basically that is wrong. What my first thought was to submit a pull request for the plugin however i do that a problem could arise with using a post variable named "chart". if i was able to just post the tgz using the main body and content-type that would be perfect instead of adding the PUT method.

**Comment by davidovich** [comment] 2018-04-27 19:59
I think that https://github.com/kiwigrid/helm-maven-plugin/pull/17 now implements that. Closing. Don't hesitate to reopen if you feel there is something missing.

**Closed by davidovich** 2018-04-27 19:59 UTC
