### ISSUE TITLE
Extra slash added to chart URL

### ISSUE THREAD

**Issue by eonicle** [kubernetes-helm/chartmuseum#136] opened 2018-05-31 14:11 UTC
ChartMuseum version: 0.7.0
Helm version: 2.9.1

I recently upgraded from 0.3.1 to 0.7.0 (using AWS S3 backend, basic auth, no multitennancy, no redis cache) - basically just upgraded docker image version. After that all chart that have extended semver version (like 0.0.0-develop) started failing to download - ChartMuseum returned malformed URLs like https://domain.com//charts/sample.tgz (notice the double slash). Removing slash by hand works fine. We tried downgrading to 0.6.0 - all started working like a charm. I am not a Go specialist, but the cause of problem might be just here: https://github.com/kubernetes-helm/chartmuseum/blob/3c628ff54e57947d273b9ffe35d7432203881861/pkg/chartmuseum/server/multitenant/cache.go#L394
This looks like the place where extra slash is added.
Important notice - all "classic" versioned charts worked fine (like 2.0.0, 1.13.27 etc.)
Anyway, thanks for your awesome project! We are so glad to have it in our production, If you need some additional info or help by any means - I am more than happy to help.

**Comment by jdolitsky** [comment] 2018-06-01 14:16
@eonicle thanks for the kind words and thanks for opening!

Unfortunately I was not able to reproduce this issue, using Helm 2.9.1 and ChartMuseum 0.7.0

My first though was that you might be using the `--chart-url` option, but even testing with that results in a OK-looking index.yaml:
```
chartmuseum --debug --port=8080 \
  --storage=local --storage-local-rootdir=$(pwd)/charts \
  --chart-url=https://domain.com/
```
```
apiVersion: v1
entries:
  mychart:
  - created: "2018-06-01T10:02:25.74676208-04:00"
    digest: f69c66148b5908087b03b60cc84ffc3df7e5ac4d5dd69c5f0b69ba34143b5bd0
    name: mychart
    urls:
    - https://domain.com/charts/mychart-0.1.0.tgz
    version: 0.1.0
  - created: "2018-06-01T10:05:47.597206592-04:00"
    digest: 036797175e8926cecb4300bf00b2373b90ba1d1cb77901d58e2530f5174c14bd
    name: mychart
    urls:
    - https://domain.com/charts/mychart-0.0.0-develop.tgz
    version: 0.0.0-develop
generated: "2018-06-01T10:08:03-04:00"
```

Could you share a little more about your setup? For example, is this running behind a proxy? Which options are you using (i.e. chart-url)? Is there possible some environment variable accidentally getting picked up by chartmuseum?

> ChartMuseum returned malformed URLs 

How are you determining this? Examining index.yaml manually, or via some Helm CLI command?

**Comment by eonicle** [comment] 2018-06-04 09:30
Hello again, and thank you for your quick response!
Here is what I get when querying for chart versions via api request (`GET https://charts.domain.my/api/charts/awesome-app `):

```json
{

        "name": "awesome-app",
        "version": "1.18.0",
        "description": "My Awesome App!",
        "apiVersion": "v1",
        "appVersion": "1.18.0",
        "urls": [
            "https://user:pass@charts.domain.my/charts/awesome-app-1.18.0.tgz"
        ],
        "created": "2018-02-05T10:55:52Z",
        "digest": "62cce0a2482fc9029c149aab2e0f394f3b7f7cc3e3dafa9900d49b5ecac7bb31"
    },
    {
        "name": "awesome-app",
        "version": "0.0.0-develop",
        "description": "My Awesome App!",
        "apiVersion": "v1",
        "appVersion": "0.0.0-develop",
        "urls": [
            "https://user:pass@charts.domain.my//charts/awesome-app-0.0.0-develop.tgz"
        ],
        "created": "2018-05-30T13:51:10Z",
        "digest": "5d5492e121528bb76774b9ed327d4f9c1668ad406f1143c27ba5517beb98858b"
}
```
Notice the double slash in URL. The same repeats for approx. 70 other charts versioned this way. As ChartMuseum returns non-vaild URL, Helm fails as well:

`$ helm fetch ewizard/awesome-app --version=0.0.0-develop
`
`
Error: Failed to fetch https://user:pass@charts.domain.my//charts/awesome-app-0.0.0-develop.tgz : 404 Not Found`
We are using ChartMuseum deployed in Rancher on Cattle orchestration behind Haproxy with SSL termination. Again, just rolling back on the same setup to version 0.6.0 works fine.

**Comment by jbrownsc** [comment] 2018-06-08 21:20
I'm seeing the same issue.  Using the following command to publish.
```
Chartmuseum version 0.7.0

helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

helm push . internal
Pushing ma-service-environment-common-0.1.3.tgz to internal...
Done.

curl http://URL/index.yaml
....
  "ma-service-environment-common": [
    {
      "apiVersion": "v1",
      "created": "2018-06-08T21:11:54.438Z",
      ....
      "name": "ma-service-environment-common",
      "urls": [
        "http://URL//charts/ma-service-environment-common-0.1.3.tgz"
      ],
      "version": "0.1.3"
    },
....
```

**Comment by jbrownsc** [comment] 2018-06-08 21:40
Passing `--disable-statefiles` or env `DISABLE_STATEFILES` seems to have fixed the issue.  I did NOT have to re-publish the chart, but I did a few times while testing, thus the updated created.

```
curl http://URL/index.yaml
....
  ma-service-environment-common:
  - apiVersion: v1
    created: "2018-06-08T21:31:59.843Z"
    ....
    name: ma-service-environment-common
    urls:
    - http://URL/charts/ma-service-environment-common-0.1.3.tgz
    version: 0.1.3
...
```

**Comment by jdolitsky** [comment] 2018-06-08 23:46
@jbrownsc thanks for the investigation into this. This seems to relate to the statefile introduced in 0.7.0. Will investigate further.

**Comment by jdolitsky** [comment] 2018-06-20 20:52
@eonicle @jbrownsc this issue should now be fixed on master. Can you try out the "latest" docker image and see if the problem is fixed on your end? Thanks!

**Comment by jdolitsky** [comment] 2018-07-06 18:18
Closing this issue. Going to cut a bugfix release. Please comment here if you still experience.

**Closed by jdolitsky** 2018-07-06 18:18 UTC
Labels: bug

**Comment by Cryptophobia** [comment] 2018-10-16 16:04
Thank you for fixing this. 0.7.1 release works like a charm!
